#+title: Mongoose

This library contains Common Lisp bindings to the [[https://mongoose.ws][Mongoose]] web server / client
library written in C. Internally Mongoose is event based and so can handle
decent concurrent load, but it is otherwise single-threaded in nature.

This library has no Common Lisp dependencies, and Mongoose itself is also
entirely self-contained.

* Table of Contents :TOC_5_gh:noexport:
- [[#compatibility][Compatibility]]
- [[#usage][Usage]]
  - [[#http-server][HTTP Server]]
    - [[#handlers][Handlers]]
    - [[#serving-static-files][Serving Static Files]]
    - [[#routing][Routing]]
    - [[#query-parameters][Query Parameters]]
    - [[#html][HTML]]
    - [[#headers][Headers]]
    - [[#tls-https][TLS (HTTPS)]]
    - [[#logging][Logging]]
  - [[#http-client][HTTP Client]]
- [[#performance][Performance]]
  - [[#measurements][Measurements]]
  - [[#tips][Tips]]
    - [[#make-alien-vs-with-alien][=make-alien= vs =with-alien=]]
- [[#related-work][Related Work]]

* Compatibility

The FFI bindings are hand-written for maximum performance and minimum dependency
load. Currently only SBCL is supported.

| Compiler  | Compiles? |
|-----------+-----------|
| SBCL      | ✅        |
| ECL       | ❌        |
| Clasp     | ❌        |
| ABCL      | ❌        |
| CCL       | ❌        |
| Clisp     | ❌        |
|-----------+-----------|
| Allegro   | ❌        |
| LispWorks | ❌        |

* Usage

See also the official [[https://mongoose.ws/documentation][Mongoose Documentation]].

As a rule, the functions and types provided here have the same names as their
underlying C ones, except that the =mg_= prefix has been stripped and underscores
are now dashes (e.g. =mg_http_serve_dir -> http-serve-dir=).

=(in-package :mongoose)= has been used for brevity in the examples below, but it's
assumed that you'll use a package nickname in your own code, perhaps =mg=.

Note also that for simplicity, no higher level Lisp API has been provided on top
of Mongoose itself. We will occasionally be using FFI primitives directly, but
you will see that this is not a stressful activity.

** HTTP Server

*** Handlers
*** Serving Static Files
*** Routing
*** Query Parameters
*** HTML
*** Headers
*** TLS (HTTPS)
*** Logging

** HTTP Client

* Performance

** Measurements

See =sample.c= for a trivial baseline server and =repl.lisp= for its Common Lisp
analogue. The following command:

#+begin_example
echo "GET http://localhost:8000/html" | vegeta attack -duration=10s -rate=0 -max-workers=4 | tee results.bin | vegeta report
#+end_example

produces these results on my 2018 ThinkPad (I write this in January 2026). The
only attempt to optimize either code was to disable logging.

| Language | Requests-per-Second |
|----------+---------------------|
| Lisp     |               23600 |
| C        |               25000 |

There are some string-related inefficiencies in the Lisp that could easily be
worked around in production code, thus I am willing to claim that for practical
purposes the FFI can be trusted not to introduce undue overhead.

** Tips

*** =make-alien= vs =with-alien=

* Related Work






